Updating redpill (bash version) to support distfiles from GitHub and curl/wget support.

diff --git a/environ/startup/redpill b/environ/startup/redpill
--- a/environ/startup/redpill
+++ b/environ/startup/redpill
@@ -1,6 +1,9 @@
 #! /bin/sh
 
-DISTFILES_SERVER="http://release.plexnet.org/distfiles"
+# Released into the Public Domain. See documentation/legal.txt for more info.
+# Author: tav <tav@espians.com>
+
+DISTFILES_SERVER="http://cloud.github.com/downloads/tav/plexnet"
 UNAME=$(uname -s)
 LSOF=$(lsof -p $$ 2> /dev/null | grep -E "/"$(basename $0)"$")
 
@@ -25,6 +28,22 @@ normal=$'\e[m'
 progress=$'\e[30;01m'##
 success=$'\e[32;01m'**
 
+have() {
+    unset -v have
+    type $1 &> /dev/null && have="yes"
+}
+
+# (have wget && export downloader='wget') || (have curl && export downloader='curl -O')
+
+have wget && _downloader="wget"
+if [ ! "$_downloader" ]; then
+    have curl && _downloader="curl -O"
+    if [ ! "$_downloader" ]; then
+        echo "!! Couldn't find either wget or curl. Please install one of them..."
+        exit
+    fi
+fi
+
 _exit_on_error() {
     echo $error Something went wrong whilst installing $TARGET !! $normal
     exit
@@ -42,7 +61,7 @@ _uncompress_tarball() {
     TARBALL_FILENAME=$TNAME-$TVERS.tar.gz
     if [ ! -f $TARBALL_FILENAME ]; then
         echo ${progress} Downloading the $TARGET Source Code ${normal}
-        curl -O ${DISTFILES_SERVER}/$TNAME/${TARBALL_FILENAME}
+        ${_downloader} ${DISTFILES_SERVER}/${TARBALL_FILENAME}
     fi
     echo ${progress} Unpacking the $TARGET Source Code ${normal}
     tar -xzf $TARBALL_FILENAME
